name: "Mozilla Addon Update Action"
description: "Update the Mozilla Firefox Update JSON File after a Release for Self Hosted Extensions."
author: "Shane"
branding:
  icon: "globe"
  color: "orange"

inputs:
  url:
    description: "Update URL with {version} in String"
    required: true
  update:
    description: "Update File Location"
    default: "update.json"
  manifest:
    description: "Manifest File Location"
    default: "manifest.json"
  version:
    description: "Addon Version"
  addon_id:
    description: "Mozilla Addon ID"

outputs:
  url:
    description: "Update URL"
  result:
    description: "Update JSON"

runs:
  using: "docker"
  image: "Dockerfile"
