# Black

[tool.black]
line-length = 119

# Ruff

[tool.ruff]
line-length = 119
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]

# Coverage

[tool.coverage.run]
omit = ["*/venv/*", "*/__pycache__/*", "*.pyc"]
source = ["src"]

# Isort

[tool.isort]
profile = "black"
lines_after_imports = 2
src_paths = ["src", "test"]
