name: "Test"

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * 1,3,5"
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug CTX github"
      #  if: ${{ !github.event.act }}
      #  continue-on-error: true
      #  env:
      #    GITHUB_CTX: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CTX"

      - name: "Create JSON"
        uses: jsdaniell/create-json@v1.2.3
        with:
          name: "update.json"
          json: '{"addons":{"test-id":{"updates":[]}}}'

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          url: https://example.com/{version}
          version: 1.0.0
          addon_id: test-id

      - name: "Validate Outputs"
        env:
          JSON: '{"addons": {"test-id": {"updates": [{"version": "1.0.0", "update_link": "https://example.com/1.0.0"}]}}}'
        run: |
          echo url: '${{ steps.test.outputs.url }}'
          if [ '${{ steps.test.outputs.url }}' != 'https://example.com/1.0.0' ];then
            echo "Invalid Output: url"
            exit 1
          fi
          echo result: '${{ steps.test.outputs.result }}'
          if [ '${{ steps.test.outputs.result }}' != '${{ env.JSON }}' ];then
            echo "Invalid Output: result"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
